/**
 * @author Nadejda Mandrescu
 */

import * as AC from '../modules/util/ActivityConstants';

const DONOR_ORGANIZATION = 'Donor Organization';
const RESPONSIBLE_ORGANIZATION = 'Responsible Organization';
const EXECUTING_AGENCY = 'Executing Agency';
const IMPLEMENTING_AGENCY = 'Implementing Agency';
const BENEFICIARY_AGENCY = 'Beneficiary Agency';
const CONTRACTING_AGENCY = 'Contracting Agency';
const DONOR_AGENCY = 'Donor';
const REGIONAL_GROUP = 'Regional Group';
const SECTOR_GROUP = 'Sector Group';

const ORG_ROLE_NAMES = [DONOR_ORGANIZATION, RESPONSIBLE_ORGANIZATION, EXECUTING_AGENCY, IMPLEMENTING_AGENCY,
  BENEFICIARY_AGENCY, CONTRACTING_AGENCY, REGIONAL_GROUP, SECTOR_GROUP];

const ACTUAL = 'Actual';
const PLANNED = 'Planned';
const COMMITMENTS = 'Commitments';
const DISBURSEMENTS = 'Disbursements';
const EXPENDITURES = 'Expenditures';
const ACTUAL_COMMITMENTS = `${ACTUAL} ${AC.COMMITMENTS}`;
const ACTUAL_DISBURSEMENTS = `${ACTUAL} ${AC.DISBURSEMENTS}`;
const ACTUAL_EXPENDITURES = `${ACTUAL} ${AC.EXPENDITURES}`;
const PLANNED_COMMITMENTS = `${PLANNED} ${AC.COMMITMENTS}`;
const PLANNED_DISBURSEMENTS = `${PLANNED} ${AC.DISBURSEMENTS}`;
const PLANNED_EXPENDITURES = `${PLANNED} ${AC.EXPENDITURES}`;
const UNALLOCATED_DISBURSEMENTS = 'Unallocated Disbursements';
const DELIVERY_RATE = 'Delivery rate';
const MTEF_PROJECTIONS = 'MTEF Projections';

const ADJUSTMENT_TYPES = [ACTUAL, PLANNED];
const ADJUSTMENT_TYPES_AP_ORDER = [PLANNED, ACTUAL];

const NEW_ACTIVITY_ID = '0';

const PROPOSED_PROJECT_COST = 'ppc';
const REVISED_PROJECT_COST = 'rpc';

const ACRONYM_DONOR_ORGANIZATION = 'DN';
const ACRONYM_EXECUTING_AGENCY = 'EA';
const ACRONYM_IMPLEMENTING_AGENCY = 'IA';
const ACRONYM_BENEFICIARY_AGENCY = 'BA';
const ACRONYM_RESPONSIBLE_ORGANIZATION = 'RO';

/** Approval status untranslated values **/
const APPROVAL_STATUS_CREATED = 'created';
const APPROVAL_STATUS_APPROVED = 'approved';
const APPROVAL_STATUS_EDITED = 'edited';
const APPROVAL_STATUS_STARTED_APPROVED = 'startedapproved';
const APPROVAL_STATUS_STARTED = 'started';
const APPROVAL_STATUS_NOT_APPROVED = 'not_approved';
const APPROVAL_STATUS_REJECTED = 'rejected';

const ON_BUDGET = 'On Budget';

const INTERNATIONAL = 'International';
const COUNTRY = 'Country';

const RELATED_DOCUMENTS = 'Related Documents';

const TMP_ENTITY_VALIDATOR = 'entity-validator';

/** Required status */
const ALWAYS_REQUIRED = 'Y';

export default Object.freeze({
  DONOR_ORGANIZATION,
  RESPONSIBLE_ORGANIZATION,
  EXECUTING_AGENCY,
  IMPLEMENTING_AGENCY,
  BENEFICIARY_AGENCY,
  CONTRACTING_AGENCY,
  DONOR_AGENCY,
  REGIONAL_GROUP,
  SECTOR_GROUP,
  ORG_ROLE_NAMES,
  ACTUAL,
  PLANNED,
  COMMITMENTS,
  DISBURSEMENTS,
  EXPENDITURES,
  ACTUAL_COMMITMENTS,
  ACTUAL_DISBURSEMENTS,
  ACTUAL_EXPENDITURES,
  PLANNED_COMMITMENTS,
  PLANNED_DISBURSEMENTS,
  PLANNED_EXPENDITURES,
  UNALLOCATED_DISBURSEMENTS,
  DELIVERY_RATE,
  MTEF_PROJECTIONS,
  ADJUSTMENT_TYPES,
  ADJUSTMENT_TYPES_AP_ORDER,
  NEW_ACTIVITY_ID,
  PROPOSED_PROJECT_COST,
  REVISED_PROJECT_COST,
  ACRONYM_DONOR_ORGANIZATION,
  ACRONYM_EXECUTING_AGENCY,
  ACRONYM_IMPLEMENTING_AGENCY,
  ACRONYM_BENEFICIARY_AGENCY,
  ACRONYM_RESPONSIBLE_ORGANIZATION,
  APPROVAL_STATUS_CREATED,
  APPROVAL_STATUS_APPROVED,
  APPROVAL_STATUS_EDITED,
  APPROVAL_STATUS_STARTED_APPROVED,
  APPROVAL_STATUS_STARTED,
  APPROVAL_STATUS_NOT_APPROVED,
  APPROVAL_STATUS_REJECTED,
  ON_BUDGET,
  INTERNATIONAL,
  COUNTRY,
  RELATED_DOCUMENTS,
  TMP_ENTITY_VALIDATOR,
  ALWAYS_REQUIRED
});
